version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend 

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports: 
      - "8090:8080"
    depends_on:
      - postgres
    networks: 
      - backend

volumes:
  postgres-data:

networks: 
  backend:
    driver: bridge
